### ISSUE TITLE
is there anyway to add new model?

### ISSUE THREAD

**Issue by iwillhappy1314** [tareq1988/wp-eloquent#10]
the example code use the default WordPress data model, is there anyway to add new model?

**Comment by dreanmer** [comment]
take a look at readme:

## Writing a Model

``` php
use \WeDevs\ORM\Eloquent\Model as Model;

class Employee extends Model {

}

var_dump( Employee::all()->toArray() ); // gets all employees
var_dump( Employee::find(1) ); // find employee with ID 1
```

The class name `Employee` will be translated into `PREFIX_employees` table to run queries. But as usual, you can override the table name.

here is more info for Eloquent: https://laravel.com/docs/5.1/eloquent

**Comment by iwillhappy1314** [comment]
@Dreanmer thanks a lot, got it.
