### ISSUE TITLE
Declaration of Database::transaction() must be compatible with ConnectionInterface::transaction()

### ISSUE THREAD

**Issue by zfarrugia** [tareq1988/wp-eloquent#42]
Hi,

This library looks great, however after including it using composer then attempting to use the **Basic Usage** example, I get the following error:

`Fatal error: Declaration of WeDevs\ORM\Eloquent\Database::transaction() must be compatible with Illuminate\Database\ConnectionInterface::transaction(Closure $callback, $attempts = 1) in /var/www/app/vendor/tareq1988/wp-eloquent/src/Eloquent/Database.php on line 12`

Here's my test code.
```
add_action('admin_init', function() {
    $db = \WeDevs\ORM\Eloquent\Database::instance();
    var_dump( $db->table('users')->find(1) );
    exit;
}, 99999);
```

I was able to get it working by adding `$attempts = 1` to the function `\WeDevs\ORM\Eloquent\Database::transaction` at Line 302 of `app/vendor/tareq1988/wp-eloquent/src/Eloquent/Database.php`.

Example:
```
/**
     * Execute a Closure within a transaction.
     *
     * @param  \Closure $callback
     *
     * @return mixed
     *
     * @throws \Exception
     */
    public function transaction(\Closure $callback, $attempts = 1)
    {
        $this->beginTransaction();
        try {
            $data = $callback();
            $this->commit();
            return $data;
        } catch (\Exception $e){
            $this->rollBack();
            throw $e;
        }
    }
```

I'm running PHP Version 5.6.34 under Docker (Image: php:5.6-apache) and WordPress 4.9.4

**Comment by daviddarke** [comment]
I'm getting this as well!

**Comment by zfarrugia** [comment]
Don't think this is directly related, as it was a year ago: https://github.com/illuminate/database/commit/fa9fcf4b237fe74f3d11be8b18e343c98bc9cfe6

However this is where the additional retry parameter was added in the dependency library.

**Comment by daviddarke** [comment]
Any ideas @tareq1988 ?
