### ISSUE TITLE
Declaration of WeDevs\ORM\Eloquent\Database::selectOne($query, $bindings = Array) must be compatible with Illuminate\Database\ConnectionInterface::selectOne

### ISSUE THREAD

**Issue by mirzazeyrek** [tareq1988/wp-eloquent#45]
Seeing this after updating the latest version:

`<br /><b>Fatal error</b>: Declaration of WeDevs\ORM\Eloquent\Database::selectOne($query, $bindings = Array) must be compatible with Illuminate\Database\ConnectionInterface::selectOne($query, $bindings = Array, $useReadPdo = true) in <b>/var/www/html/clone.staging.com/wp-content/mu-plugins/vendor/tareq1988/wp-eloquent/src/Eloquent/Database.php</b> on line <b>12</b><br />`

**Comment by roskno** [comment]
Hi,

I've just installed this project and it's throwing the same error:

`[09-May-2019 11:35:42 UTC] PHP Fatal error:  Declaration of WeDevs\ORM\Eloquent\Database::selectOne($query, $bindings = Array) must be compatible with Illuminate\Database\ConnectionInterface::selectOne($query, $bindings = Array, $useReadPdo = true) in /Applications/MAMP/htdocs/woosync/wp-content/plugins/atum-export-pro/vendor/tareq1988/wp-eloquent/src/Eloquent/Database.php on line 12`

Can anybody help me, please?
