### ISSUE TITLE
How does it connect to db?

### ISSUE THREAD

**Issue by JuicyLung91** [tareq1988/wp-eloquent#50]
How does this connect it to the right database ? There is no config.

I´ve got en error when i try this
`$db = \WeDevs\ORM\Eloquent\Database::instance();

var_dump( $db->table('users')->find(1) );`

The error says: 
`
Fatal error: Uncaught Error: Call to a member function get_results() on null in /var/www/html/test/vendor/tareq1988/wp-eloquent/src/Eloquent/Database.php:136 Stack trace: #0 /var/www/html/test/vendor/illuminate/database/Query/Builder.php(2082):

**Comment by Tofandel** [comment]
It needs to be used within wordpress $wpdb need to be defined
