### ISSUE TITLE
Issues with case-sensitive folder names

### ISSUE THREAD

**Issue by mirzazeyrek** [tareq1988/wp-eloquent#8]
This folder names are not working on php 5.4.13 due to case-sentitivity.

\WeDevs\ORM\Eloquent\Model as Model;
\WeDevs\ORM\Eloquent\WP\User as User;

This lines are causing fatal error class not found error with those folders:

vendor/tareq1988/wp-eloquent/src/wp 
vendor/tareq1988/wp-eloquent/src/eloquent

Issue fixed after renaming folder names like this:

vendor/tareq1988/wp-eloquent/src/WP
vendor/tareq1988/wp-eloquent/src/Eloquent

**Comment by tareq1988** [comment]
Which OS are you trying in? Haven't found any issues on Mac and Linux so far.

**Comment by mirzazeyrek** [comment]
CentOS 6.5 (Final)

**Comment by helarqjsc** [comment]
It should be easy to fix it by renaming folders in this repo to match namespace exactly. I don't see any reason not to do it.

**Comment by mirzazeyrek** [comment]
there is already pull request for this.

**Comment by tareq1988** [comment]
The pull request got merged.
